language: node_js
deploy:
  provider: npm
  email: nedved.yang@gmail.com
  api_key:
    secure: j+pwKxUf9jF0y/fMH2IfX3NnzcflwKxfEDUslH3Muf1XO0eooA+jOZq1Tfj58G79yt90t/hLn4uuUhEuR+Ddk1FXleodFWrurgA6bVBYu/b53/jMjWrQ/4x+jjy1RyIruHoMYRvN8+9rTAVu5OXBLa2xHGBK9gR+LyBkyaM1qWszMBoxOVoV3cduZFM+kFyjJGxUz+revvWKIqTqdMtexKlubJ2M18QNTvxS5h5XoMF8BtNm7Xl4mnXYT0YUdFTrniHyWdfhBF6IuBP0cfhn6oet3BexNhRUOVpSFn3ujjQGEAsRcIaicLbobRSosq++sI2SB+D2EGlcZWeNyMTDlMeXsMl8YUyS7HqSKOHEbbhLi22ts6z7W7YLnSpHmcFlokoUSoKHbMoa+WCNhlCve5wETyDILEYf0N0Pq5nmsVAxdj6pcExDLpoq5CHh/dORXRmoXwhN+02bzuL7Fn3vmrqP1IQKjemePba3fsa6jE28XUD4FJbJxPwGE2dJzlAczGhuP5BC4Q7ei7qioUWDQjCFI4qXCwU5ccInOSCcLu14Rq/cnsmrgA1gdJkuUiP4XcESHuBPnxoczafFmzOYY2yBF+LcIDXSIQ2fgdK3f+xIzcEnpkchz+sVhvFDm2xhIo/5wkdLNLU59TLth47ues5zF0hKJiZM3ZMVnLXHxJ8=
  on:
    tags: true
    repo: Nedvedyy/logging
api_key: 
email: nedved.yang@gmail.com
provider: npm
